name: editor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  fast_color_picker: ^0.1.1
  http:
  url_launcher: ^6.1.6
  flutter_arc_text: ^0.5.0
  google_fonts: ^3.0.1
  photofilters: ^3.0.1
  screenshot: ^1.2.3
  emoji_picker_flutter: ^1.3.1
  image_picker: ^0.8.5+3
  image_cropper: ^1.3.1
  share_plus: ^4.0.8
  gallery_saver: ^2.3.2
  flutter_staggered_grid_view: ^0.4.0
  path_provider: ^2.0.3
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.5
  extended_image: ^6.2.1
  flutter_colorpicker: ^1.0.3
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  google_mobile_ads: ^2.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - fonts/
    - images/newIcons/
    - images/college/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Another Flight
      fonts:
        - asset: fonts/Another Flight.otf
    - family: ArimaKoshi
      fonts:
        - asset: fonts/ArimaKoshi-Regular.otf
    - family: beautiful
      fonts:
        - asset: fonts/beatiful.otf
    - family: Brown Choco
      fonts:
        - asset: fonts/Brown Choco.ttf

    - family: Calligraffitti
      fonts:
        - asset: fonts/Calligraffitti-Regular.ttf

    - family: DSFette
      fonts:
        - asset: fonts/DSFetteGotisch.ttf

    - family: Exo
      fonts:
        - asset: fonts/evanescent.ttf

    - family: FingerPaint
      fonts:
        - asset: fonts/FingerPaint-Regular.ttf


    - family: Hartford
      fonts:
        - asset: fonts/Hartford Demo.ttf


    - family: Herdrey
      fonts:
        - asset: fonts/herdrey demo.ttf


    - family: Jelle
      fonts:
        - asset: fonts/Jellee-Roman.ttf


    - family: Junction
      fonts:
        - asset: fonts/Junction-regular.otf

    - family: JustBe
      fonts:
        - asset: fonts/JustBeDemo-Regular.ttf

    - family: LillyMae
      fonts:
        - asset: fonts/LillyMae-Regular.otf

    - family: LuxuriousScript
      fonts:
        - asset: fonts/LuxuriousScript-Regular.ttf

    - family: Margueritas
      fonts:
        - asset: fonts/Margueritas.ttf


    - family: MINUS
      fonts:
        - asset: fonts/MINUS_CRE.ttf

    - family: Rhonde
      fonts:
        - asset: fonts/Rhonde-Free.otf

    - family: RubikWetPaint
      fonts:
        - asset: fonts/RubikWetPaint-Regular.ttf

    - family: Satanyc
      fonts:
        - asset: fonts/Satanyc Demoniac St.ttf


    - family: ShortStack
      fonts:
        - asset: fonts/ShortStack-Regular.ttf


    - family: TribalScript
      fonts:
        - asset: fonts/Tribal Script.ttf
    - family: AEROBIC
      fonts:
        - asset: fonts/AEROBIC.ttf
    - family: Astral Sisters
      fonts:
        - asset: fonts/Astral Sisters.ttf
    - family: AwayStress
      fonts:
        - asset: fonts/AwayStress.ttf
    - family: BaguetteBread
      fonts:
        - asset: fonts/BaguetteBread.ttf
    - family: BeigeWave
      fonts:
        - asset: fonts/BeigeWave.ttf

    - family: Bigcups
      fonts:
        - asset: fonts/Bigcups.otf

    - family: Caniago
      fonts:
        - asset: fonts/Caniago.ttf


    - family: Cartline Brush
      fonts:
        - asset: fonts/Cartline Brush.otf


    - family: deserted-canyon
      fonts:
        - asset: fonts/deserted-canyon.ttf


    - family: DOLPHINES
      fonts:
        - asset: fonts/DOLPHINES.otf


    - family: edinburg
      fonts:
        - asset: fonts/edinburg.ttf

    - family: Gesturally
      fonts:
        - asset: fonts/Gesturally.ttf

    - family: GlowingSkin
      fonts:
        - asset: fonts/GlowingSkin.ttf

    - family: GOLDEN
      fonts:
        - asset: fonts/GOLDEN.otf

    - family: Highbary Sunfest
      fonts:
        - asset: fonts/Highbary Sunfest.otf

    - family: Hirarki Signature
      fonts:
        - asset: fonts/Hirarki Signature.ttf

    - family: Hugshack
      fonts:
        - asset: fonts/Hugshack.otf

    - family: Januaryta
      fonts:
        - asset: fonts/Januaryta.ttf
    - family: Journal Republica
      fonts:
        - asset: fonts/Journal Republica.ttf
    - family: just-because
      fonts:
        - asset: fonts/just-because.ttf
    - family: Jute Basket
      fonts:
        - asset: fonts/Jute Basket.otf
    - family: LowMagnetic
      fonts:
        - asset: fonts/LowMagnetic.ttf
    - family: MONGONDOW
      fonts:
        - asset: fonts/MONGONDOW.otf
    - family: Moonlight
      fonts:
        - asset: fonts/Moonlight.otf
    - family: morriles
      fonts:
        - asset: fonts/morriles.ttf
    - family: Listhon
      fonts:
        - asset: fonts/Listhon.ttf
    - family: NightMelody
      fonts:
        - asset: fonts/NightMelody.ttf
    - family: phenomicon
      fonts:
        - asset: fonts/phenomicon.ttf
    - family: Palagio
      fonts:
        - asset: fonts/Palagio.otf
    - family: Posting
      fonts:
        - asset: fonts/Posting.ttf
    - family: Qapitaly
      fonts:
        - asset: fonts/Qapitaly.ttf


    - family: QEBIL
      fonts:
        - asset: fonts/QEBIL.otf


    - family: Qomarun
      fonts:
        - asset: fonts/Qomarun.ttf

    - family: QueenChallenge
      fonts:
        - asset: fonts/QueenChallenge.ttf

    - family: QUINOR
      fonts:
        - asset: fonts/QUINOR.otf

    - family: robosapien
      fonts:
        - asset: fonts/robosapien.ttf

    - family: RockAway
      fonts:
        - asset: fonts/RockAway.ttf

    - family: Romile
      fonts:
        - asset: fonts/Romile.otf

    - family: Scary Envision
      fonts:
        - asset: fonts/Scary Envision.ttf

    - family: Selebgram
      fonts:
        - asset: fonts/Selebgram.ttf

    - family: Sketch
      fonts:
        - asset: fonts/Sketch.ttf
    - family: SouthernAire
      fonts:
        - asset: fonts/SouthernAire.ttf
    - family: stay-tuned
      fonts:
        - asset: fonts/stay-tuned.ttf

    - family: CRONICLE
      fonts:
        - asset: fonts/CRONICLE.otf
    - family: VASQUZ
      fonts:
        - asset: fonts/VASQUZ.otf
    - family: walkthemoon
      fonts:
        - asset: fonts/walkthemoon.ttf
