name: editor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  fast_color_picker: ^0.1.1
  http: ^0.13.5
  url_launcher: ^6.1.7
  flutter_arc_text: ^0.5.0
  google_fonts: ^3.0.1
  photofilters: ^3.0.1
  screenshot: ^1.2.3
  emoji_picker_flutter: ^1.5.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  share_plus: ^6.3.0
  gallery_saver: ^2.3.2
  flutter_staggered_grid_view: ^0.6.2
  path_provider: ^2.0.11
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  extended_image: ^6.3.4
  flutter_colorpicker: ^1.0.3
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  google_mobile_ads: ^2.3.0
  smooth_page_indicator: ^1.0.0+2
  spring_button: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - images/
    - fonts/
    - images/newIcons/
    - images/college/


  fonts:
    - family: Another Flight
      fonts:
        - asset: fonts/Another Flight.ttf
    - family: ArimaKoshi
      fonts:
        - asset: fonts/ArimaKoshi-Regular.ttf
    - family: beautiful
      fonts:
        - asset: fonts/beatiful.ttf
    - family: Brown Choco
      fonts:
        - asset: fonts/Brown Choco.ttf

    - family: Calligraffitti
      fonts:
        - asset: fonts/Calligraffitti-Regular.ttf

    - family: DSFette
      fonts:
        - asset: fonts/DSFetteGotisch.ttf

    - family: Exo
      fonts:
        - asset: fonts/evanescent.ttf

    - family: FingerPaint
      fonts:
        - asset: fonts/FingerPaint-Regular.ttf


    - family: Hartford
      fonts:
        - asset: fonts/Hartford Demo.ttf


    - family: Herdrey
      fonts:
        - asset: fonts/herdrey demo.ttf


    - family: Jelle
      fonts:
        - asset: fonts/Jellee-Roman.ttf


    - family: Junction
      fonts:
        - asset: fonts/Junction-regular.ttf

    - family: JustBe
      fonts:
        - asset: fonts/JustBeDemo-Regular.ttf

    - family: LillyMae
      fonts:
        - asset: fonts/LillyMae-Regular.ttf

    - family: LuxuriousScript
      fonts:
        - asset: fonts/LuxuriousScript-Regular.ttf

    - family: Margueritas
      fonts:
        - asset: fonts/Margueritas.ttf


    - family: MINUS
      fonts:
        - asset: fonts/MINUS_CRE.ttf

    - family: Rhonde
      fonts:
        - asset: fonts/Rhonde-Free.ttf

    - family: RubikWetPaint
      fonts:
        - asset: fonts/RubikWetPaint-Regular.ttf

    - family: Satanyc
      fonts:
        - asset: fonts/Satanyc Demoniac St.ttf


    - family: ShortStack
      fonts:
        - asset: fonts/ShortStack-Regular.ttf


    - family: TribalScript
      fonts:
        - asset: fonts/Tribal Script.ttf
    - family: AEROBIC
      fonts:
        - asset: fonts/AEROBIC.ttf
    - family: Astral Sisters
      fonts:
        - asset: fonts/Astral Sisters.ttf
    - family: AwayStress
      fonts:
        - asset: fonts/AwayStress.ttf
    - family: BaguetteBread
      fonts:
        - asset: fonts/BaguetteBread.ttf
    - family: BeigeWave
      fonts:
        - asset: fonts/BeigeWave.ttf

    - family: Bigcups
      fonts:
        - asset: fonts/Bigcups.ttf

    - family: Caniago
      fonts:
        - asset: fonts/Caniago.ttf


    - family: Cartline Brush
      fonts:
        - asset: fonts/Cartline Brush.ttf


    - family: deserted-canyon
      fonts:
        - asset: fonts/deserted-canyon.ttf

    - family: DOLPHINES
      fonts:
        - asset: fonts/DOLPHINES.ttf
    - family: edinburg
      fonts:
        - asset: fonts/edinburg.ttf

    - family: Gesturally
      fonts:
        - asset: fonts/Gesturally.ttf

    - family: GlowingSkin
      fonts:
        - asset: fonts/GlowingSkin.ttf

    - family: GOLDEN
      fonts:
        - asset: fonts/GOLDEN.ttf

    - family: Highbary Sunfest
      fonts:
        - asset: fonts/Highbary Sunfest.ttf

    - family: Hirarki Signature
      fonts:
        - asset: fonts/Hirarki Signature.ttf

    - family: Hugshack
      fonts:
        - asset: fonts/Hugshack.ttf

    - family: Januaryta
      fonts:
        - asset: fonts/Januaryta.ttf
    - family: Journal Republica
      fonts:
        - asset: fonts/Journal Republica.ttf
    - family: just-because
      fonts:
        - asset: fonts/just-because.ttf
    - family: Jute Basket
      fonts:
        - asset: fonts/Jute Basket.ttf
    - family: LowMagnetic
      fonts:
        - asset: fonts/LowMagnetic.ttf
    - family: MONGONDOW
      fonts:
        - asset: fonts/MONGONDOW.ttf
    - family: Moonlight
      fonts:
        - asset: fonts/Moonlight.ttf
    - family: morriles
      fonts:
        - asset: fonts/morriles.ttf
    - family: Listhon
      fonts:
        - asset: fonts/Listhon.ttf
    - family: NightMelody
      fonts:
        - asset: fonts/NightMelody.ttf
    - family: phenomicon
      fonts:
        - asset: fonts/phenomicon.ttf
    - family: Palagio
      fonts:
        - asset: fonts/Palagio.ttf
    - family: Posting
      fonts:
        - asset: fonts/Posting.ttf
    - family: Qapitaly
      fonts:
        - asset: fonts/Qapitaly.ttf


    - family: QEBIL
      fonts:
        - asset: fonts/QEBIL.ttf


    - family: Qomarun
      fonts:
        - asset: fonts/Qomarun.ttf

    - family: QueenChallenge
      fonts:
        - asset: fonts/QueenChallenge.ttf

    - family: QUINOR
      fonts:
        - asset: fonts/QUINOR.ttf

    - family: robosapien
      fonts:
        - asset: fonts/robosapien.ttf

    - family: RockAway
      fonts:
        - asset: fonts/RockAway.ttf

    - family: Romile
      fonts:
        - asset: fonts/Romile.ttf

    - family: Scary Envision
      fonts:
        - asset: fonts/Scary Envision.ttf

    - family: Selebgram
      fonts:
        - asset: fonts/Selebgram.ttf

    - family: Sketch
      fonts:
        - asset: fonts/Sketch.ttf
    - family: SouthernAire
      fonts:
        - asset: fonts/SouthernAire.ttf
    - family: stay-tuned
      fonts:
        - asset: fonts/stay-tuned.ttf

    - family: CRONICLE
      fonts:
        - asset: fonts/CRONICLE.ttf
    - family: VASQUZ
      fonts:
        - asset: fonts/VASQUZ.ttf
    - family: walkthemoon
      fonts:
        - asset: fonts/walkthemoon.ttf
    - family: a4_36
      fonts:
        - asset: fonts/a4_36.ttf
    - family: e4_38
      fonts:
        - asset: fonts/e4_38.ttf        

    - family: b4_AF
      fonts:
        - asset: fonts/b4_AF.ttf
    - family: d4_B0
      fonts:
        - asset: fonts/d4_B0.ttf
    - family: w23830ass
      fonts:
        - asset: fonts/w23830ass.ttf
    - family: s
      fonts:
        - asset: fonts/s.ttf
    - family: ArbFONTS-QTSManga-SemiBold
      fonts:
        - asset: fonts/ArbFONTS-QTSManga-SemiBold.ttf
    - family: ArbFONTS-aref-bold
      fonts:
        - weight: 900
        - asset: fonts/ArbFONTS-aref-bold.ttf
    - family: ArbFONTS-aref-regular
      fonts:
        - weight: 500
        - asset: fonts/ArbFONTS-aref-regular.ttf 
    - family: ArbFONTS-ArefRuqaa-Bold
      fonts:
        - weight: 900
        - asset: fonts/ArbFONTS-ArefRuqaa-Bold.ttf
    - family: ArbFONTS-ArefRuqaa-Regular
      fonts:
        - weight: 500
        - asset: fonts/ArbFONTS-ArefRuqaa-Regular.ttf    
    - family: ArbFONTS-arefrusqsaa-bold
      fonts:
        - weight: 900
        - asset: fonts/ArbFONTS-arefrusqsaa-bold.ttf
    - family: ArbFONTS-arefruqasas-regular
      fonts:
        - weight: 500
        - asset: fonts/ArbFONTS-arefruqasas-regular.ttf 
    - family: ArbFONTS-bein-ar-normal
      fonts:
        - weight: 900
        - asset: fonts/ArbFONTS-bein-ar-normal.ttf
    - family: ArbFONTS-OMNES-ARABIC-REGULAR
      fonts:
        - weight: 500
        - asset: fonts/ArbFONTS-OMNES-ARABIC-REGULAR.ttf                           
    - family: ArbFONTS-Ubuntu-Arabic_R
      fonts:
        - asset: fonts/ArbFONTS-Ubuntu-Arabic_R.ttf     
